config/routes.rb
Rails.application.routes.draw do

  resources :badges

  resources :challenges
  
  resources :participants

  resources :achievements

  resources :dream_tags

  get 'sleep_guide' => 'sleep_guide#index'

  resources :board_messages

  resources :voters

  resources :categories

  resources :comments

  resources :posts do
      resources :comments, shallow: true
  end

  resources :group_users

  resources :groups

  resources :friendships

  resources :logs

  resources :meanings do
      member do
          get 'mark_as_spam'
          get 'vote_up'
          get 'vote_down'
      end
  end

  resources :dream_signs

  devise_for :users, controllers: {
          sessions: 'users/sessions',
          registrations: 'users/registrations',
          omniauth_callbacks: 'users/omniauth_callbacks'
  }, :path => "users"

  devise_scope :user do
      get 'user/:id/profile' => 'users/registrations#show', as: 'user_profile'
      get 'user/:id/delete_avatar' => 'users/registrations#delete_avatar', as: 'delete_avatar'
    end

  resources :users do
      resources :sleep_logs
      resources :dreams
      resources :characters
      resources :locations
  end
  resources :widgets

  root 'welcome#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base

    belongs_to :commentable, polymorphic: true
    has_many :comments, :as => :commentable
    
    belongs_to :user
    
    has_many :voters, :as => :votable
    has_many :users, through: :voters, :as => :votable
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  include Pundit
  rescue_from Pundit::NotAuthorizedError, with: :comment_not_authorized

  def index
      @comments = Comment.all
  end

  def new
      @comment = Comment.new
      authorize @comment
  end

  def create
      @comment = Comment.new(comment_params)
      authorize @comment
      if params[:commentable_type] == "Post"
          @commentable    = Post.find(params[:commentable_id])
      elsif params[:commentable_type] == "Dream"
          @commentable    = Dream.find(params[:commentable_id])
      elsif params[:commentable_type] == "Comment"
          @commentable    = Comment.find(params[:commentable_id])
      end
      @comment.user = current_user
      @comment.commentable = @commentable
      if @comment.save  
        flash[:notice] = "Comment published."  
      else  
        flash[:notice] = "Unable to publish your comment."  
      end 
      if params[:commentable_type] == "Post"
          redirect_to post_path(params[:commentable_id])
      elsif params[:commentable_type] == "Dream"
          redirect_to user_dream_path(user_id:Dream.find(params[:commentable_id]).user_id , id: params[:commentable_id])
      elsif params[:commentable_type] == "Comment"
          redirect_to parent_post(@comment)
      end
  end

  def edit
      set_comment
      authorize @comment
  end

  def update
      set_comment
      authorize @comment
      @comment.save
  end

  def delete
      set_comment
      authorize @comment
  end
  

  def destroy
      set_comment
      authorize @comment
      @comment.destroy
  end

  def mark_as_spam
      set_comment
      authorize @comment
  end
  
  private
      def parent_post(c)
          if c.has_attribute?(:commentable_id)
              parent_post(c.commentable)
          elsif c.instance_of?(Dream)
              user_dream_path(user_id: c.user_id, id: c.id)
          else
              c
          end
      end
      
      def set_comment
          @comment = Comment.find(params[:id])
      end
      
      def comment_params
          params.require(:comment).permit(:content, :votes, :user_id, :commentable_id, :commentable_type, :spam)
      end
      
      def comment_not_authorized
        flash[:alert] = "You aren't allowed to do that."
        redirect_to(request.referrer || root_path)
      end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<% if comment.user.avatar.exists? %>
    <%= image_tag comment.user.avatar.url(:medium), class:'avatar' %>
<% else %>
    <%= image_tag comment.user.gravatar_url(default: 'identicon'), class:'avatar' %>
<% end %>
<%= link_to comment.user.username, user_profile_path(comment.user) %><br />
<%= comment.content %><br />
<small><%= time_ago_in_words(comment.created_at) %> ago | <span class="badge"><%= comment.votes %> <i class="fa fa-heart-o"></i></span></small>

<% if current_user && !comment.voters.find_by_user_id(current_user.id) && comment.user != current_user %>
<%= link_to voters_path(post_id: @post.id, votable_id: comment.id, votable_type: 'Comment', user_id: current_user.id, positive: true), :method => :post, class:'btn btn-primary' do %>Vote up <i class="fa fa-thumbs-o-up"></i><% end %>
<%= link_to voters_path(post_id: @post.id, votable_id: comment.id, votable_type: 'Comment', user_id: current_user.id, positive: false), :method => :post, class:'btn btn-primary' do %>Vote down <i class="fa fa-thumbs-o-down"></i><% end %>
<% elsif current_user && comment.voters.find_by_user_id(current_user.id) %>
<%= link_to voter_path(post_id: @post.id, votable_id: comment.id, votable_type: 'Comment', user_id: current_user.id), :method => :delete, class:'btn btn-danger' do %>Delete my vote <i class="fa fa-minus-circle"></i><% end %>
<% end %>

<% if current_user %>
    <%= link_to new_comment_path(commentable_type: "Comment", commentable_id: comment.id), class:'btn btn-success' do %>Reply <i class="fa fa-reply"></i><% end %>
    <% if policy(comment).edit? %>
        <%= link_to edit_comment_path(comment), class: 'btn btn-warning' do %><i class="fa fa-pencil"></i> Edit<% end %>
    <% end %>
<% end %><br /><hr />
<div class="nested" style="padding-left: 2em;"><%= render comment.comments %></div>

app/views/comments/_form.html.erb
<%= form_for @comment do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
 <div class="new_form ">
	 <div class="field" data-no-turbolink>
	    <%= f.label :content %><br>
	    <%= f.text_area :content, class: 'form-control' %>
	    <%= hidden_field_tag(:commentable_type, "Comment") %>
	    <%= hidden_field_tag(:commentable_id, params[:commentable_id]) %>
	    <br />
	 </div>
	  
	 <div class="actions">
	    <%= f.submit "Submit", class:'btn btn-primary' %>
	  </div>
  </div>
  <% end %>

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/delete.html.erb
<h1>Comments#delete</h1>
<p>Find me in app/views/comments/delete.html.erb</p>

app/views/comments/destroy.html.erb
<h1>Comments#destroy</h1>
<p>Find me in app/views/comments/destroy.html.erb</p>

app/views/comments/edit.html.erb
<h1>Editing your comment</h1>
<%= render 'form' %>

app/views/comments/index.html.erb
<h1>Comments#index</h1>
<p>Find me in app/views/comments/index.html.erb</p>

app/views/comments/mark_as_spam.html.erb
<h1>Comments#mark_as_spam</h1>
<p>Find me in app/views/comments/mark_as_spam.html.erb</p>

app/views/comments/new.html.erb
<h2>Add your comment</h2>
<%= render 'comments/form' %>

app/views/comments/update.html.erb
<h1>Comments#update</h1>
<p>Find me in app/views/comments/update.html.erb</p>

app/views/comments/vote_down.html.erb
<h1>Comments#vote_down</h1>
<p>Find me in app/views/comments/vote_down.html.erb</p>

app/views/comments/vote_up.html.erb
<h1>Comments#vote_up</h1>
<p>Find me in app/views/comments/vote_up.html.erb</p>