config/routes.rb
Rails.application.routes.draw do

  resources :badges

  resources :challenges
  
  resources :participants

  resources :achievements

  resources :dream_tags

  get 'sleep_guide' => 'sleep_guide#index'

  resources :board_messages

  resources :voters

  resources :categories

  resources :comments

  resources :posts do
      resources :comments, shallow: true
  end

  resources :group_users

  resources :groups

  resources :friendships

  resources :logs

  resources :meanings do
      member do
          get 'mark_as_spam'
          get 'vote_up'
          get 'vote_down'
      end
  end

  resources :dream_signs

  devise_for :users, controllers: {
          sessions: 'users/sessions',
          registrations: 'users/registrations',
          omniauth_callbacks: 'users/omniauth_callbacks'
  }, :path => "users"

  devise_scope :user do
      get 'user/:id/profile' => 'users/registrations#show', as: 'user_profile'
      get 'user/:id/delete_avatar' => 'users/registrations#delete_avatar', as: 'delete_avatar'
    end

  resources :users do
      resources :sleep_logs
      resources :dreams
      resources :characters
      resources :locations
  end
  resources :widgets

  root 'welcome#index'

end

app/models/group.rb
class Group < ActiveRecord::Base
    has_many :group_users
    has_many :users, through: :group_users
    has_many :board_messages
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

  include Pundit
  rescue_from Pundit::NotAuthorizedError, with: :group_not_authorized

  def index
      @groups = Group.all
  end

  def new
     @group = Group.new
  end

  def create
     @group  = Group.new(group_params)
     @creator = @group.group_users.build(:user_id => current_user.id, :manager => true) 
     authorize @creator 
     
     if @group.save
         @creator 
         redirect_to group_path(@group)
     else 
         redirect_to new_group_path
     end
  end

  def edit
      @group = Group.find(params[:id])
  end

  def update
      @group = Group.find(params[:id])
      if @group.update(group_params)
          redirect_to @group
      end
  end

  def delete
      @group = Group.find(params[:id])
  end

  def destroy
      @group = Group.find(params[:id])
  end
  
  def show
      @group = Group.find(params[:id])
      
      #friends
      @friends = Array.new
      current_user.friends.each do |friend|
          if current_user.inverse_friends.include?(friend) && !@group.users.include?(friend)
              @friends << friend
          end 
      end 
      
      #followers
      @followers = Array.new
      current_user.inverse_friends.each do |friend|
          if !current_user.friends.include?(friend) && !@group.users.include?(friend)
              @followers << friend
          end 
      end 
      
      #following
      @following = Array.new
      current_user.friends.each do |friend|
          if !current_user.inverse_friends.include?(friend) && !@group.users.include?(friend)
              @following << friend
          end 
      end 
      
  end
  
  private
      def group_params
          params.require(:group).permit(:name, :description, :public)
      end
      
      def group_not_authorized
        flash[:alert] = "You aren't allowed to do that."
        redirect_to(request.referrer || root_path)
      end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/delete.html.erb
<h1>Groups#delete</h1>
<p>Find me in app/views/groups/delete.html.erb</p>

app/views/groups/destroy.html.erb
<h1>Groups#destroy</h1>
<p>Find me in app/views/groups/destroy.html.erb</p>

app/views/groups/edit.html.erb
<h1><%= @group.name %></h1>
<%= form_for(@group) do |f| %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name, autofocus: true, class:'form-control' %>
  </div>
  
  <div class="field">
    <%= f.label :public %><br />
    <%= f.check_box :public, class:'form-control' %>
  </div>
  
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description, class:'form-control' %>
  </div>
    
  <div class="actions">
    <%= f.submit "Create group", class:'btn btn-primary' %>
  </div>
<% end %>

app/views/groups/index.html.erb
<%= link_to new_group_path, style:'float: right;', class:'btn btn-primary' do %><i class="fa fa-plus"></i> Create Group<% end %>
<h1>Groups</h1>

<% Group.all.each do |g| %>
    <h3><%= link_to g.name, g %></h3>
    <p><%= g.users.count %> member(s)</p>
    <hr />
<% end %>

app/views/groups/new.html.erb
<h1>Create a group</h1>
<%= form_for(@group) do |f| %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name, autofocus: true, class:'form-control' %>
  </div>
  
  <div class="field">
    <%= f.label :public %><br />
    <%= f.check_box :public, class:'form-control' %>
  </div>
  
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description, class:'form-control' %>
  </div>
    
  <div class="actions">
    <%= f.submit "Create group", class:'btn btn-primary' %>
  </div>
<% end %>

app/views/groups/show.html.erb
<h1><i class="fa fa-users"></i> <%= @group.name.capitalize %></h1>
<p><%= @group.description.capitalize %></p>
<% if (@group.public || (current_user and @group.group_users.find_by_user_id(current_user.id)) || current_user.role.name == "admin") %>
    <% if policy(@group).edit? %>
        <%= link_to edit_group_path(@group), class: 'btn btn-warning', style:"float: right;" do %><i class="fa fa-pencil"></i> Edit<% end %>
    <% end %>
    <% if ((current_user and !@group.group_users.find_by_user_id(current_user.id)) && (@group.public || current_user.role.name == "admin")) %>
        <%= link_to group_users_path(group_id: @group.id, user_id: current_user.id, manager:false), :method => :post, class:'btn btn-primary' do %><i class="fa fa-plus"></i> Join<% end %>
    <% end %>
    <% if (current_user and @group.group_users.find_by_user_id(current_user.id)) %>
        <%= link_to group_user_path(group_id: @group.id, user_id: current_user.id), method: :delete, class: 'btn btn-danger' do %><i class="fa fa-minus"></i> Leave Group<% end %>
    <% end %>
    <% if policy(@group).add_member? %>
        <h3>Add new Users (αlpha => will be moved to a dialog)</h3>
        <ul class="nav nav-tabs" role="tablist" id="add_a_member">
          <li role="presentation" class="active"><a href="#friends" role="tab" aria-controls="friends" data-toggle="tab"><i class="fa fa-heart"></i> Friends</a></li>
          <li role="presentation"><a href="#following" role="tab" aria-controls="following" data-toggle="tab"><i class="fa fa-star"></i> Following</a></li>
          <li role="presentation"><a href="#followers" role="tab" aria-controls="followers" data-toggle="tab"><i class="fa fa-cloud"></i> Followers</a></li>
        </ul>
        <div class="tab-content">
            <div class="friends tab-pane active" role="tabpanel" id="friends">
                <h1><i class="fa fa-heart"></i> Friends</h1>
                <% @friends.each do |u|  #TODO show user's friends and a search box in a dialog #issue28 %>
                    <%= link_to user_profile_path(u) do %>
                        <% if u.avatar.exists? %>
                            <%= image_tag u.avatar.url(:medium), class: 'mini-avatar' %>
                        <% else %>
                            <%= image_tag u.gravatar_url(default: 'identicon'), class: 'mini-avatar' %>
                        <% end %>
                    <% end %>
                    <%= link_to u.username, u %>
                    <% if policy(@group).add_member? && u != current_user %>
                        <%= link_to "Add member", group_users_path(group_id: @group.id, user_id: u.id, manager:false), :method => :post, class:'btn btn-success' %>
                    <% end %><br />
                <% end %>
            </div>

            <div class="following tab-pane" role="tabpanel" id="following">
                <h1><i class="fa fa-star"></i> Following</h1>
                <% @following.each do |u|  #TODO show user's friends and a search box in a dialog #issue28 %>
                    <%= link_to user_profile_path(u) do %>
                        <% if u.avatar.exists? %>
                            <%= image_tag u.avatar.url(:medium), class: 'mini-avatar' %>
                        <% else %>
                            <%= image_tag u.gravatar_url(default: 'identicon'), class: 'mini-avatar' %>
                        <% end %>
                    <% end %>
                    <%= link_to u.username, u %>
                    <% if policy(@group).add_member? && u != current_user %>
                        <%= link_to "Add member", group_users_path(group_id: @group.id, user_id: u.id, manager:false), :method => :post, class:'btn btn-success' %>
                    <% end %><br />
                <% end %>
            </div>

            <div class="followers tab-pane" role="tabpanel" id="followers">
                <h1><i class="fa fa-cloud"></i> Followers</h1>
                <% @followers.each do |u|  #TODO show user's friends and a search box in a dialog #issue28 %>
                    <%= link_to user_profile_path(u) do %>
                        <% if u.avatar.exists? %>
                            <%= image_tag u.avatar.url(:medium), class: 'mini-avatar' %>
                        <% else %>
                            <%= image_tag u.gravatar_url(default: 'identicon'), class: 'mini-avatar' %>
                        <% end %>
                    <% end %>
                    <%= link_to u.username, u %>
                    <% if policy(@group).add_member? && u != current_user %>
                        <%= link_to "Add member", group_users_path(group_id: @group.id, user_id: u.id, manager:false), :method => :post, class:'btn btn-success' %>
                    <% end %><br />
                <% end %>
            </div>
        </div>
        <hr />
    <% end %>
    <div class="row">
        <div class="col-xs-6">
            <h3>Members</h3>
            <% @group.users.each do |user| %>
                <%= link_to user_profile_path(user) do %>
                    <% if user.avatar.exists? %>
                        <%= image_tag user.avatar.url(:medium), class: 'mini-avatar' %>
                    <% else %>
                        <%= image_tag user.gravatar_url(default: 'identicon'), class: 'mini-avatar' %>
                    <% end %>
                <% end %>
                <%= link_to user.username, user_profile_path(user) %>
                <% if policy(@group).remove_member? && user != current_user %>
                    <%= link_to "Remove member", group_user_path(group_id: @group.id, user_id: user.id), method: :delete, class:'btn btn-danger' %>
                <% end %><br />
            <% end %>
        </div>
        <div class="col-xs-6">
            <h3>Board</h3>
            <% @group.board_messages.all.order(:created_at).each do |m| %>
                <%= m.content %><br />
                <%= link_to user_profile_path(m.user) do %>
                    <% if m.user.avatar.exists? %>
                        <%= image_tag m.user.avatar.url(:medium), class: 'mini-avatar' %>
                    <% else %>
                        <%= image_tag m.user.gravatar_url(default: 'identicon'), class: 'mini-avatar' %>
                    <% end %>
                <% end %>
                <%= link_to m.user.username, m.user %><br />
                <%= time_ago_in_words m.created_at %> ago<br />
                <% if policy(m).edit? %>
                    <%= link_to edit_board_message_path(m), class: 'btn btn-warning' do %><i class="fa fa-pencil"></i> Edit<% end %>
                <% end %>
                <hr />
            <% end %>
            <hr />
            <%= form_for BoardMessage.new do |f| %>
              <div class="form-inline" style="width:100%;" >
                  <div class="form-group" style="width:80%;">
                    <%= f.text_field :content, class:'form-control',style:"width:100%;" %>
                    </div>
                    <%= hidden_field_tag(:group_id, @group.id) %>
                    <%= hidden_field_tag(:user_id, current_user.id) %>
                   <div class="form-group">
                    <%= f.submit "Send", class:'btn btn-primary' %>
                   </div>
               </div>
            <% end %>
        </div>
    </div>
    <script>
    $('#add_a_member a').click(function (e) {
      e.preventDefault()
      $(this).tab('show')
    })
    </script>
<% end %>

app/views/groups/update.html.erb
<h1>Groups#update</h1>
<p>Find me in app/views/groups/update.html.erb</p>