config/routes.rb
Rails.application.routes.draw do

  resources :badges

  resources :challenges
  
  resources :participants

  resources :achievements

  resources :dream_tags

  get 'sleep_guide' => 'sleep_guide#index'

  resources :board_messages

  resources :voters

  resources :categories

  resources :comments

  resources :posts do
      resources :comments, shallow: true
  end

  resources :group_users

  resources :groups

  resources :friendships

  resources :logs

  resources :meanings do
      member do
          get 'mark_as_spam'
          get 'vote_up'
          get 'vote_down'
      end
  end

  resources :dream_signs

  devise_for :users, controllers: {
          sessions: 'users/sessions',
          registrations: 'users/registrations',
          omniauth_callbacks: 'users/omniauth_callbacks'
  }, :path => "users"

  devise_scope :user do
      get 'user/:id/profile' => 'users/registrations#show', as: 'user_profile'
      get 'user/:id/delete_avatar' => 'users/registrations#delete_avatar', as: 'delete_avatar'
    end

  resources :users do
      resources :sleep_logs
      resources :dreams
      resources :characters
      resources :locations
  end
  resources :widgets

  root 'welcome#index'

end

app/models/achieved.rb
class Achieved < ActiveRecord::Base
    belongs_to :achievement
    belongs_to :user
end

app/models/category.rb
class Category < ActiveRecord::Base
    has_many :posts
end

app/models/challenge.rb
class Challenge < ActiveRecord::Base
    has_many :participants, dependent: :destroy
    has_many :users, through: :participants
    
    has_attached_file :icon, :styles => { :medium => "300x300>", :thumb => "100x100>" },
                         s3_server_side_encryption: :aes256
    validates_attachment_content_type :icon, :content_type => /\Aimage\/.*\Z/
end

app/models/character.rb
class Character < ActiveRecord::Base
    has_many :dream_characters, :dependent => :destroy
    has_many :dreams, through: :dream_characters
    belongs_to :user

    has_attached_file :icon, :styles => { :medium => "300x300>", :thumb => "100x100>" }, s3_permissions: :private,
                         s3_server_side_encryption: :aes256
    validates_attachment_content_type :icon, :content_type => /\Aimage\/.*\Z/
end

app/models/comment.rb
class Comment < ActiveRecord::Base

    belongs_to :commentable, polymorphic: true
    has_many :comments, :as => :commentable
    
    belongs_to :user
    
    has_many :voters, :as => :votable
    has_many :users, through: :voters, :as => :votable
end

app/models/dream.rb
class Dream < ActiveRecord::Base
    belongs_to :user
    has_many :dream_characters, :dependent => :destroy
    has_many :characters, through: :dream_characters
    accepts_nested_attributes_for :dream_characters

    has_many :dream_locations, :dependent => :destroy
    has_many :locations, through: :dream_locations
    accepts_nested_attributes_for :dream_locations

    has_many :comments, :as => :commentable

    has_many :voters, :as => :votable
    has_many :users, through: :voters, :as => :votable

    has_many :dream_has_tags, :dependent => :destroy
    has_many :dream_tags, through: :dream_has_tags
    accepts_nested_attributes_for :dream_has_tags

    has_attached_file :icon, :styles => { :medium => "300x300>", :thumb => "100x100>" }, s3_permissions: :private,
                         s3_server_side_encryption: :aes256
    validates_attachment_content_type :icon, :content_type => /\Aimage\/.*\Z/
end

app/models/dream_sign.rb
class DreamSign < ActiveRecord::Base
    belongs_to :user
    has_many :meanings
end

app/models/dream_tag.rb
class DreamTag < ActiveRecord::Base
  has_many :dream_has_tags, :dependent => :destroy
  has_many :dreams, through: :dream_has_tags
  accepts_nested_attributes_for :dream_has_tags
  belongs_to :user
end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
    belongs_to :user  
    belongs_to :friend, :class_name => 'User' 
end

app/models/group.rb
class Group < ActiveRecord::Base
    has_many :group_users
    has_many :users, through: :group_users
    has_many :board_messages
end

app/models/group_user.rb
class GroupUser < ActiveRecord::Base
    belongs_to :group
    belongs_to :user
end

app/models/location.rb
class Location < ActiveRecord::Base
    has_many :dream_locations, :dependent => :destroy
    has_many :dreams, through: :dream_locations
    belongs_to :user

    has_attached_file :icon, :styles => { :medium => "300x300>", :thumb => "100x100>" }, s3_permissions: :private,
                         s3_server_side_encryption: :aes256
    validates_attachment_content_type :icon, :content_type => /\Aimage\/.*\Z/
end

app/models/log.rb
class Log < ActiveRecord::Base
    belongs_to :user
end

app/models/meaning.rb
class Meaning < ActiveRecord::Base
    belongs_to :user
    belongs_to :dream_sign
    
    has_many :voters, :as => :votable
    has_many :users, through: :voters, :as => :votable
end

app/models/post.rb
class Post < ActiveRecord::Base
    belongs_to :category

    has_many :comments, :as => :commentable

    belongs_to :user
    has_many :voters, :as => :votable
    has_many :users, through: :voters, :as => :votable
end

app/models/role.rb
class Role < ActiveRecord::Base
    has_many :users
end

app/models/sleep_log.rb
class SleepLog < ActiveRecord::Base
    belongs_to :user
    validates :date, uniqueness: true
    order(:date)
    
    def log_dreams
      @dreams = Array.new
      @dreams = self.user.dreams.where(date: self.date).find_each
      puts @dreams
      return @dreams.count
    end
    
    def log_hours
        if (self.end_time.to_i > self.start_time.to_i)
            return ((self.end_time.to_i - self.start_time.to_i)/3600).round
        elsif (self.end_time.to_i == self.start_time.to_i)
            return 0
        else
            return (((24*3600-self.start_time.to_i) + self.end_time.to_i)/3600).round
        end
    end
    
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable, :omniauthable, :omniauth_providers => [:twitter]

  include Gravtastic
  gravtastic

  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

  has_many :posts

  has_many :participants, dependent: :destroy
  has_many :challenges, through: :participants

  has_many :achieveds, dependent: :destroy
  has_many :achievements, through: :achieveds

  has_many :dreams
  has_many :characters
  has_many :locations

  has_many :voters, as: :votable
  has_many :posts, through: :voters, :source => :votable, :source_type => 'Post'
  has_many :comments, through: :voters, :source => :votable, :source_type => 'Comment'

  has_many :group_users
  has_many :groups, through: :group_users
  has_many :board_messages


  has_many :friendships
  has_many :friends, :through => :friendships

  has_many :inverse_friendships, :class_name => "Friendship", :foreign_key => "friend_id"
    has_many :inverse_friends, :through => :inverse_friendships, :source => :user

  belongs_to :role

  has_many :meanings
  has_many :dream_signs

  has_many :sleep_logs

  has_many :logs

  attr_accessor :login

  validates :username,
    :presence => true,
    :uniqueness => { :case_sensitive => false }


  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions.to_h).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    else
      where(conditions.to_h).first
    end
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.points = 50
      user.bio = ''
      user.public_sleep_log = true
      user.public_profile = true
      user.role     = Role.find_by_name('registered')
      user.confirmed_at = Time.now
      user.avatar   = auth.info.image
      user.email    = auth.info.nickname+'@change.me'
      user.password = Devise.friendly_token[0,20]
      user.username = auth.info.nickname
      #user.image = auth.info.image # assuming the user model has an image
    end
  end
end

app/models/voter.rb
class Voter < ActiveRecord::Base
    belongs_to :user
    belongs_to :votable, polymorphic: true
end

app/models/widget.rb
class Widget < ActiveRecord::Base
end

app/views/shared/_left_sidebar_default.html.erb
<h3>Sidebar</h3>

app/views/shared/_navigation.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only"><i class="fa fa-burguer"></i></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/"><%= image_tag "logo_head.png", style:'display:inline; height:28px; width: auto;', alt:'Oneironauts' %> Oneironauts</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to posts_path do %><i class="fa fa-newspaper-o"></i> Blog <% end %></li>
        <li><%= link_to dream_signs_path do%><i class="fa fa-book"></i> Dream Dictionary<%end%></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-paper-plane-o"></i> Guides <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><%= link_to "Sleep Habits", sleep_guide_path %></li>
            <li class="divider"></li>
          </ul>
        </li>
        <% if current_user %>
            <li><%= link_to groups_path do%><i class="fa fa-users"></i> Groups<%end%></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-globe"></i> Quests <span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li><%= link_to challenges_path do%><i class="fa fa-gamepad"></i> Challenges<%end%></li>
                <li><%= link_to achievements_path do%><i class="fa fa-trophy"></i> Achievements<%end%></li>
              </ul>
            </li>
            
            <li class="dropdown">
                      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                          <% if current_user.avatar.exists? %>
                              <%= image_tag current_user.avatar.url(:medium), class: 'mini-avatar' %>
                          <% else %>
                              <%= image_tag current_user.gravatar_url(default: 'identicon'), class: 'mini-avatar' %>
                          <% end %> Me <span class="caret"></span></a>
                      <ul class="dropdown-menu" role="menu">
                            <li><%= link_to user_profile_path(current_user.id) do%><i class="fa fa-user"></i> Profile<% end %></li>
                             <li><%= link_to user_dreams_path(current_user.id) do%><i class="fa fa-cloud"></i> Dream Journal<%end%></li>
                             <li><%= link_to user_sleep_logs_path(current_user.id) do%><i class="fa fa-bar-chart"></i> Sleep Log<%end%></li>
                      </ul>
            </li>
            <li><%= link_to destroy_user_session_path, method: :delete, :class => 'navbar-link' do%><i class="fa fa-sign-out"></i> Log out<%end%></li>
        <% else %>
            <li><%= link_to new_user_session_path do %><i class="fa fa-sign-in"></i> Log in<% end %></li>
            <li><%= link_to new_user_registration_path do %><i class="fa fa-user-plus"></i> Sign up<% end %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>