config/routes.rb
Rails.application.routes.draw do

  resources :badges

  resources :challenges
  
  resources :participants

  resources :achievements

  resources :dream_tags

  get 'sleep_guide' => 'sleep_guide#index'

  resources :board_messages

  resources :voters

  resources :categories

  resources :comments

  resources :posts do
      resources :comments, shallow: true
  end

  resources :group_users

  resources :groups

  resources :friendships

  resources :logs

  resources :meanings do
      member do
          get 'mark_as_spam'
          get 'vote_up'
          get 'vote_down'
      end
  end

  resources :dream_signs

  devise_for :users, controllers: {
          sessions: 'users/sessions',
          registrations: 'users/registrations',
          omniauth_callbacks: 'users/omniauth_callbacks'
  }, :path => "users"

  devise_scope :user do
      get 'user/:id/profile' => 'users/registrations#show', as: 'user_profile'
      get 'user/:id/delete_avatar' => 'users/registrations#delete_avatar', as: 'delete_avatar'
    end

  resources :users do
      resources :sleep_logs
      resources :dreams
      resources :characters
      resources :locations
  end
  resources :widgets

  root 'welcome#index'

end

app/models/sleep_log.rb
class SleepLog < ActiveRecord::Base
    belongs_to :user
    validates :date, uniqueness: true
    order(:date)
    
    def log_dreams
      @dreams = Array.new
      @dreams = self.user.dreams.where(date: self.date).find_each
      puts @dreams
      return @dreams.count
    end
    
    def log_hours
        if (self.end_time.to_i > self.start_time.to_i)
            return ((self.end_time.to_i - self.start_time.to_i)/3600).round
        elsif (self.end_time.to_i == self.start_time.to_i)
            return 0
        else
            return (((24*3600-self.start_time.to_i) + self.end_time.to_i)/3600).round
        end
    end
    
end

app/controllers/sleep_logs_controller.rb
class SleepLogsController < ApplicationController

  respond_to :html, :json

#  require 'rasem'
  def index
      @sleep_logs = current_user.sleep_logs
      respond_to do |format|
        format.html # show.html.erb
        format.json { render :json => @sleep_logs.order(:date).to_json(:methods => [:log_dreams, :log_hours]) }
      end
      
#      @img = Rasem::SVGImage.new(300,300) do
#        
#        circle 20, 20, 5
#        circle 50, 50, 5
#        line 20, 20, 50, 50
#      end

  end

  def show
      @log = User.find(params[:user_id]).sleep_logs.find(params[:id])
  end

  def create
      @log = SleepLog.create(sleep_log_params)
      @log.user_id = current_user.id
      if @log.save
          redirect_to user_sleep_logs_path(current_user.id)
      else 
          flash[:alert] = 'You can only enter a Sleep Log Entry per date'
          redirect_to user_sleep_logs_path(current_user.id)
      end
  end

  def new
      @log = SleepLog.new
  end

  def destroy
      @log = User.find(params[:user_id]).sleep_logs.find(params[:id])
      @log.destroy
      redirect_to user_sleep_logs_path(current_user.id)
  end

  def delete
      @log = User.find(params[:user_id]).sleep_logs.find(params[:id])
  end

  def edit
      @log = User.find(params[:user_id]).sleep_logs.find(params[:id])
  end

  def update
      @log = User.find(params[:user_id]).sleep_logs.find(params[:id])
      if @log.update(sleep_log_params)
          redirect_to user_sleep_logs_path(current_user.id)
      else 
          flash[:alert] = 'You can only enter a Sleep Log Entry per date'
          redirect_to user_sleep_logs_path(current_user.id)
      end
  end
  
  private
      def sleep_log_params
          params.require(:sleep_log).permit(:date, :user_id, :start_time, :end_time)
      end
end

app/helpers/sleep_logs_helper.rb
module SleepLogsHelper

    def slept_hours(l)
        if (l.end_time.to_i > l.start_time.to_i)
            return ((l.end_time.to_i - l.start_time.to_i)/3600).round
        elsif (l.end_time.to_i == l.start_time.to_i)
            return 0
        else
            return (((24*3600-l.start_time.to_i) + l.end_time.to_i)/3600).round
        end
    end

end

app/views/sleep_logs/delete.html.erb
<h1>SleepLogs#delete</h1>
<p>Find me in app/views/sleep_logs/delete.html.erb</p>

app/views/sleep_logs/destroy.html.erb
<h1>SleepLogs#destroy</h1>
<p>Find me in app/views/sleep_logs/destroy.html.erb</p>

app/views/sleep_logs/edit.html.erb
<h1>Edit Sleep Log Entry</h1>
<%= form_for [current_user, @log] do |f| %>
    <%= f.label :date %><br />
    <%= f.date_select(:date,:start_year => 1950, class:'form-control') %><br />
    <%= f.label :start_time %><br />
    <%= f.time_select(:start_time, class:'form-control') %><br />
    <%= f.label :end_time %><br />
    <%= f.time_select(:end_time, class:'form-control') %><br />
    <%= f.submit "Submit", class:'btn btn-primary' %>
<% end %>

app/views/sleep_logs/index.html.erb
<%= link_to new_user_sleep_log_path, style:'float: right;', class:'btn btn-primary' do %><i class="fa fa-plus"></i> Add Entry<% end %>
<h1>Your Sleep Log</h1>
<hr />
<div class="well">
    <h3>Keep up with the good sleeping</h3>
    <p>Sleeping has many benefits for your health. Improves memory, lengthen life expectancy improves attention and mood, prevents overweight... To learn more about how to sleep well, just visit our Sleeping Habits Guide.</p>
    <%= link_to sleep_guide_path, class:'btn btn-success' do %><i class="fa fa-moon-o"></i> Learn More<% end %>
</div>
<% current_user.sleep_logs.order(:date).each do |l| %>
    <%= link_to user_sleep_log_path(user_id: current_user.id, id: l.id), method: :delete, class:'btn btn-danger', style:'float: right; margin-left: 5px;' do %><i class="fa fa-trash"></i> Delete<% end %>
    <%= link_to edit_user_sleep_log_path(user_id: current_user.id, id: l.id), class:'btn btn-warning', style:'float: right;' do %><i class="fa fa-pencil"></i> Edit<% end %>
    <%= l.date %>: <%= l.start_time %> -  <%= l.end_time %> [<%= slept_hours(l) %> hour(s)]
    <% if(l.user.dreams.where(date: l.date)) %>
        <% l.user.dreams.where(date: l.date).find_each do |d| %>
            <%= link_to d.title, user_dream_path(user_id:current_user.id, id: d.id) %>
        <% end %>
    <% end %>
    <hr />
<% end %>
<div class="charts" style="text-align: center;">
    <div id="dream_chart" style="height: 300px; width: 45%; display: inline-block;"></div>
    <div id="hours_chart" style="height: 300px; width: 45%; display: inline-block;"></div>
</div>
<script>
       var url = "/users/<%=current_user.id%>/sleep_logs.json"
       var dream_json= $.getJSON(url, null, function(data) {
           var get_dream_data = dream_json.responseText;
           new Morris.Bar({
             element: 'dream_chart',
             data: $.parseJSON((get_dream_data)),
             xkey: 'date',
             resize: true,
             smooth: false,
             ykeys: ['log_dreams'],
             barColors: ['#3F61BA'],
             labels: ['Dreams']
               }); done();
           }); 
       var hour_json= $.getJSON(url, null, function(data) {
           var get_hour_data = hour_json.responseText;
           new Morris.Line({
             element: 'hours_chart',
             data: $.parseJSON((get_hour_data)),
             xkey: 'date',
             pointSize: 5,
             resize: true,
             smooth: false,
             ykeys: ['log_hours'],
             lineColors: ['#f3c247'],
             labels: ['Slept Hours']
             }); done();  
           });         
</script>

app/views/sleep_logs/new.html.erb
<h1>New Sleep Log Entry</h1>
<%= form_for [current_user, SleepLog.new] do |f| %>
    <%= f.label :date %><br />
    <%= f.date_select(:date,:start_year => 1950, class:'form-control') %><br />
    <%= f.label :start_time %><br />
    <%= f.time_select(:start_time, class:'form-control') %><br />
    <%= f.label :end_time %><br />
    <%= f.time_select(:end_time, class:'form-control') %><br />
    <%= f.submit "Submit", class:'btn btn-primary' %>
<% end %>

app/views/sleep_logs/show.html.erb
<h1><%= @log.date %> Sleep Log</h1>
<%= @log.start_time %><br />
<%= @log.end_time %><br />
<% if(@log.user.dreams.where(date: @log.date)) %>
    <% @log.user.dreams.where(date: @log.date).find_each do |d| %>
        <%= link_to d.title, d %>
    <% end %>
<% end %>

app/views/sleep_logs/update.html.erb
<h1>SleepLogs#update</h1>
<p>Find me in app/views/sleep_logs/update.html.erb</p>